# 1. Introduction to NumPy

* What NumPy is and why it’s important for numerical computations in Python.
Installation of NumPy (pip install numpy).
Understanding its role in data science, machine learning, and scientific computing.

In [1]:
pip install numpy


# 2. Arrays in NumPy

* Understanding the concept of ndarray (N-dimensional array).
Creating arrays using np.array(), np.zeros(), np.ones(), np.arange(), and np.linspace().
Array indexing and slicing.

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print (arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr= np.zeros(5)
print (arr)
print (type(arr))


[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr= np.ones(5)
print (arr)
print (type(arr))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


* 0D array

In [13]:
import numpy as np

arr = np.array(42)

print(arr)

42


* 1D array

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


* 2D array

In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


* 3D array

In [19]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [21]:
import numpy as np 

#create an array 
arr= np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [25]:
import numpy as np

# Generate 10 numbers between 0 and 1
array = np.linspace(0, 2, num=10)
print(array)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [29]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [31]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]
