# 7. Random Number Generation

* Generating random numbers using np.random (e.g., np.random.rand(), np.random.randint()).
Seeding random number generation (np.random.seed()).
Random sampling, shuffling, and permutations.

In [1]:
import numpy as np

random_number = np.random.rand()
print(random_number)

random_array = np.random.rand(5)
print(random_array)

random_matrix = np.random.rand(2, 3)
print(random_matrix)


0.6692909270115597
[0.57643247 0.87192286 0.16483333 0.40229216 0.54981351]
[[0.38910597 0.94215841 0.30590847]
 [0.54964142 0.17213255 0.6450097 ]]


In [3]:
import numpy as np

random_integer = np.random.randint(0, 11)
print(random_integer)

random_array = np.random.randint(0, 11, size=5)
print(random_array)

random_matrix = np.random.randint(0, 11, size=(2, 3))
print(random_matrix)


7
[ 5  6  7 10  4]
[[10  8  0]
 [ 0 10  8]]


In [5]:
import numpy as np

np.random.seed(42)

random_numbers = np.random.rand(5)
print(random_numbers)


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [7]:
import numpy as np

population = np.arange(1, 11)

sample = np.random.choice(population, size=3, replace=False)

print("Population:", population)
print("Sample:", sample)


Population: [ 1  2  3  4  5  6  7  8  9 10]
Sample: [1 2 9]


In [9]:
import numpy as np

arr = np.arange(1, 11)

np.random.shuffle(arr)

print("Original Array:", np.arange(1, 11))
print("Shuffled Array:", arr)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Shuffled Array: [10  3  1  7  9  6  4  8  2  5]


In [11]:
import itertools

elements = [1, 2, 3]

permutations = list(itertools.permutations(elements))

print("Permutations:")
for permutation in permutations:
    print(permutation)


Permutations:
(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [13]:
import numpy as np

arr = np.arange(1, 11)

random_permutation = np.random.permutation(arr)

print("Original Array:", arr)
print("Random Permutation:", random_permutation)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Random Permutation: [ 2  8  7  3  9  1  4  5  6 10]


# Broadcasting

* Understanding how NumPy handles operations between arrays of different shapes.
Rules of broadcasting (e.g., matching dimensions, aligning axes).

In [15]:
#Multiplying a 2D Array by a 1D Array


import numpy as np

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
arr1d = np.array([10, 20, 30])

# Multiply the 2D array by the 1D array
result = arr2d * arr1d

print(result)


[[ 10  40  90]
 [ 40 100 180]]


In [17]:
# Broadcasting with Arrays of Different Shapes


import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[10], [20]])

# Add the two arrays
result = arr1 + arr2

print(result)


[[11 12]
 [23 24]]
