# 5. Array Manipulation

* Indexing and slicing: understanding multi-dimensional arrays.
Masking (logical indexing based on conditions).
Fancy indexing (using arrays of indices to select elements).

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Accessing elements
print(arr[0]) 
print(arr[-1]) 

# Slicing
print(arr[1:3]) 
print(arr[1:]) 
print(arr[:3])

1
5
[2 3]
[2 3 4 5]
[1 2 3]


In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print(arr[0, 0]) 
print(arr[1, 2]) 

# Slicing
print(arr[0, 1:]) 
print(arr[1, :2])

1
6
[2 3]
[4 5]


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

mask = arr > 3

print(arr[mask])  


[4 5]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

indices = np.array([0, 2, 4])
print(arr[indices])

[1 3 5]


In [11]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

row_indices = np.array([0, 1])
col_indices = np.array([0, 2])
print(arr[row_indices, col_indices])

[1 6]


# 6. Mathematical Functions

* Universal functions (ufuncs) like np.add(), np.subtract(), np.multiply().
Statistical functions: np.mean(), np.median(), np.std(), np.var(), np.min(), np.max().
Linear algebra functions: np.dot(), np.matmul(), np.linalg.inv(), np.linalg.eig().

In [13]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add the arrays
result = np.add(arr1, arr2)

print(result)

[5 7 9]


In [15]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Subtract arr2 from arr1
result = np.subtract(arr1, arr2)

print(result)

[-3 -3 -3]


In [17]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Multiply the arrays
result = np.multiply(arr1, arr2)

print(result) 

[ 4 10 18]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
print(mean) 

3.0


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
median = np.median(arr)
print(median) 

3.0


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
std_dev = np.std(arr)
print(std_dev)

1.4142135623730951


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
variance = np.var(arr)
print(variance)

2.0


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
min_val = np.min(arr)
print(min_val) 

1


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
max_val = np.max(arr)
print(max_val)

5


In [31]:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)
print(dot_product)

32


In [33]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

matrix_product = np.matmul(arr1, arr2)
print(matrix_product)


[[19 22]
 [43 50]]


In [35]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

inverse = np.linalg.inv(arr)
print(inverse)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

eigenvalues, eigenvectors = np.linalg.eig(arr)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
